#!/usr/bin/env python

import sys
import os
import logging

import mapzen.whosonfirst.index

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-m', '--mode', dest='mode', action='store', default='files', help='...')

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    def cb(f):
        props = f["properties"]
        logging.info("index %s" % props["wof:id"])

    idx = mapzen.whosonfirst.index.indexer(options.mode, cb)
    idx.index_paths(args)
