#!/usr/bin/env python

import sys
import os
import logging
import geojson

import mapzen.whosonfirst.index

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-s', '--source', dest='source', action='store', default=None, help='Directory to read files from')
    opt_parser.add_option('-M', '--mapshaper', dest='mapshaper', action='store', default=None, help='...')

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    source = os.path.abspath(options.source)
    indexer = mapzen.whosonfirst.index.geojson(source, mapshaper=options.mapshaper)

    for path in args:

       path = os.path.abspath(path)
       fh = open(path, "r")
       
       feature = geojson.load(fh)
       indexer.index_feature(feature)


